version: '3'

services:
  db:
    image: couchdb
    build: 
      context: db
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
        - ./dbdata:/opt/couchdb/data
  apigl:
    image: apigl
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      - DB_USER=admin
      - DB_PASS=password
      - DB_NAME=equipamen
      - DB_URL=db
      - DB_PORT=5984
